### ISSUE TITLE
design different footer?

### ISSUE THREAD

**Issue by frank4600** [danfickle/openhtmltopdf#172]
defines different footers for the first page, or last page?

**Comment by rototor** [comment]
You mean having a different footer element for the first or the last page? This is possible using standard CSS rules.

E.g.

```css

@page {
  size: A4;
  @bottom-center {
    content: element(footer_normal);
  }
}

@page:first {
@bottom-center {
    content: element(footer_first);
  }
}

@page:last {
@bottom-center {
    content: element(footer_last);
  }
}

#footer_first {
   position:running(footer_first);
}

#footer_last {
   position:running(footer_last);
}

#footer_normal {
  position:running(footer_normal);
}
```
```html
<div id=footer_normal>Normal Footer</div>
<div id=footer_lastl>Last Footer</div>
<div id=footer_first>First Footer</div>
```

This should work. Note: content:element(name) and position:running(name) must have the same ```name```, if you give the div's the same id is not important.
