### ISSUE TITLE
Use custom font

### ISSUE THREAD

**Issue by aleksandr-m** [danfickle/openhtmltopdf#20]
Any way to use custom font? There is `PdfBoxFontResolver`, but currently don't see how to add custom font to it.

**Comment by danfickle** [comment]
Currently, the easiest way is to use a font-face rule in your css. Note: Only truetype fonts are supported and this will not currently work in the Java2D renderer - see #17

``` css
@font-face {
    font-family: "Noto Sans";
    src: url("NotoSans-Regular.ttf"); /* Use an absolute or relative url. */
}

/* Later, use font as named: */
body {
    font-family: 'Noto Sans', sans-serif;
}
```

If you want to add it in code instead, let me know and I'll give you a code sample.
