### ISSUE TITLE
PDF not displaying asian fonts such as Thai

### ISSUE THREAD

**Issue by devturnip** [danfickle/openhtmltopdf#296]
I have my fonts in stored in installed on my machine, as well as in a /tmp/fonts folder and in the html file im specifying it this way

`  @font-face {
  font-family: 'noto';
  /* Note: No trailing format tag is allowed. */
  src: url(/tmp/fonts/NotoSerifThai-Regular.ttf);
  font-weight: normal;
  font-style: normal;

  * {
            font-family: sans-serif, "noto";
        }
`
I'm having trouble trying to get the Thai fonts to be displayed.

**Comment by devturnip** [comment]
If it helps:

![image](https://user-images.githubusercontent.com/36265457/48888347-5f266d80-ee6d-11e8-9070-ad5f2e48c706.png)

**Comment by danfickle** [comment]
Try:
````css
@font-face {
  font-family: 'noto';
  src: url(file:///tmp/fonts/NotoSerifThai-Regular.ttf);
  font-weight: normal;
  font-style: normal;
}
*
{
  font-family: sans-serif, "noto";
}
````
Note the addition of the file protocol and the closing bracket after the font-face block.

If that doesn’t work, could you post the builder code and log output?
