### ISSUE TITLE
Caption of table not working as expected

### ISSUE THREAD

**Issue by danielblazquez** [danfickle/openhtmltopdf#340]
The caption tag of a table is not the same width as the table parent and the caption text is not centered correctly.
```css
caption{
  text-align: center;
  display: table-caption;
}
table{
  width: 25%;
}
```

```html
<table>
  <caption>Caption text</caption>
  <tr><th>Text</th><th>Text</th><th>Text</th></tr>
  <tr><td>Text</td><td>Text</td><td>Text</td></tr>
</table>

```
