### ISSUE TITLE
How can i set every page different height in multi page export

### ISSUE THREAD

**Issue by yellowjian** [danfickle/openhtmltopdf#356]
as the title

**Comment by danfickle** [comment]
You can use the `size` property inside a `@page` rule. You could use named page feature for example to target different pages. See page features on the wiki for an example.

If this doesn’t help, can you give us a little more info on what you’re trying to achieve?

**Comment by yellowjian** [comment]
for example: maybe i want set page 1 height is 600px, page 2 height is 1000px, how can i achieve it?   @page rule just only set height for every page the same height.

**Comment by syjer** [comment]
hi @yellowjian in the wiki (https://github.com/danfickle/openhtmltopdf/wiki/Page-features) you can see the section:

```css
@page named {
 ...
}
```

and then a little bit below:

```css
named-page {
  page-break-before: always;
  /* The page property allows us to marry up an element with a @page rule. */
  page: named;
  display: block;
}
```

Then, it's used in the html below as:

```html
<named-page>
Some content on a named page<br/>
More content on a named page<br/>
</named-page>
```

So you can do the following (didn't tested, but it's an educated guess :)):

css:

```css

@page page1 {
 size: 600px 600px;
}

@page page2 {
  size: 1000px 1000px;
}

named-page1 {
  page-break-before: always;
  page: page1;
  display: block;
}

named-page2 {
  page-break-before: always;
  page: page2;
  display: block;
}
```

Then in the html:

```
<named-page1>my page 1</named-page1>
<named-page2>my page 2</named-page2>
```
