### ISSUE TITLE
How can we add some text before page break ( I mean in the first page )

### ISSUE THREAD

**Issue by bhaskermca** [danfickle/openhtmltopdf#456]
I have a requirement where i can show content in the first page for a table with text as ( Continued on Page 2) and In page 2 i have to show ( Continued from Page 1 This i can achieved )

Do you have specific tag which supports in the first page.

I tried with <tfoot> but it is showing at the end of the second page also. 

Please suggest is there any way for this to achieve

**Comment by danfickle** [comment]
Have you tried:
````css
@page {
  @top-center {
     content: "I am not page 1";
  }
}
@page:first {
  @top-center {
     content: "I am page 1!";
  }
}
````
