### ISSUE TITLE
How to insert Footer/Header when tranforming HTML to PDF

### ISSUE THREAD

**Issue by ZahirKali** [danfickle/openhtmltopdf#64]
Hi Daniel,

I use openhtmltopdf tool to transforme HTML to PDF. I am searching a way to insert header/footer in the PDF (the header/footer must appear in all the PDF pages, so i cannot insert header/footer in the HTML page).

Is it possible to do this please ?

**Comment by achuinard** [comment]
Yes, you have to use the @bottom-center CSS property inside of the @page block.

See http://stackoverflow.com/questions/7206748/apply-margin-to-running-css-position for an example.

**Comment by poliveira89** [comment]
I think this issue is similar to #58 an it contains a link for StackOverflow.

The second answer it worked for me.
```css
@page {
    /* headers*/
    @top-left {
        content: "Left header";
    } 
    @top-right {
        content: "Right header";
    }

    /* footers */
    @bottom-left {
        content: "Lorem ipsum";
    } 
    @bottom-right {
        content: "Page " counter(page) " of " counter(pages);
    }
}
```
The code from the snippet before is based on John Mark [answer](http://stackoverflow.com/a/27567608/2075782)
