### ISSUE TITLE
Multiple background images on first page

### ISSUE THREAD

**Issue by baedorf** [danfickle/openhtmltopdf#649]
I need to combine/place several images on first page using following css:

```css
@page:first {
    @top-center {
         content: 'first';
     }
     background-image: url(background.png), url(image13.png);
}
```

According to css this should be valid and allowed.
Creating a PDF produces following message
````
com.openhtmltopdf.css-parse WARNING:: (f#inline_style_1) Found 2 value(s) for background-image when 1 value(s) were expected at line 52. Skipping declaration.
```` 
How to solve this?
